# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

########################################################################
#                       CONFIGURACION DEL PROMPT                       #
########################################################################

	WHITE='\e[38;5;15m'
	BLUE='\e[38;5;45m'
	PURPLE='\e[38;5;97m'
	GREEN='\e[38;5;120m'
	YELLOW='\e[38;5;3m'
	RED='\e[1;38;5;1m'

    #te +%H:%M`) ------- Hora actual -------
	function r() {
		#CLOCK=$CLOCK'\n\e[1;38;5;15m'
		#CLOCK=$CLOCK`tput sc``tput cup 0 0`               # Posicion inicio
		#CLOCK=$CLOCK`date +" %A, %d de %B del %Y "` 		# Fecha actual
  		#CLOCK=$CLOCK`date +"%I:%M %p"` 	 	            # Hora actual y cambio a rojo
  		#CLOCK=$CLOCK`tput rc`                             # Posicion final
		#CLOCK="$CLOCK"$PURPLE       		                # change to light blue
		#CLOCK="$CLOCK""\n${PURPLE}(`date +%H:%M`)"   	    # Horar de entrada al terminal
        echo -e "\e[1m${WHITE}`date +" %A, %d de %B del %Y "`(`date +%H:%M`)\e[0m"
	}

	# --------- PROMPT ------------

		#PS1="\e[1m${PURPLE}(`date +%H:%M`) ${BLUE}\u ${WHITE}at ${GREEN}\h ${WHITE}in ${YELLOW}\w"
        PS1="${BLUE}\u ${WHITE}at ${GREEN}\h ${WHITE}in ${YELLOW}\w"

	# ----------- GIT -----------

		if test -z "$WINELOADERNOEXEC"
		then
			GIT_EXEC_PATH="$(git --exec-path 2>/dev/null)"
			COMPLETION_PATH="${GIT_EXEC_PATH%/libexec/git-core}"
			COMPLETION_PATH="${COMPLETION_PATH%/lib/git-core}"
			COMPLETION_PATH="$COMPLETION_PATH/share/git/completion"
			if test -f "$COMPLETION_PATH/git-prompt.sh"
			then
				. "$COMPLETION_PATH/git-completion.bash"
				. "$COMPLETION_PATH/git-prompt.sh"
				PS1="$PS1"$BLUE  	# change color to cyan
				PS1="$PS1"'`__git_ps1`\n'   	# bash function
			fi
		fi

		function getGit() {
			
				if [ $GIT_RESULT ]
				then
					PS1="$PS1"$BLUE  	# change color to cyan
				else
					PS1="$PS1"$RED  	# change color to cyan
				fi
				PS1="$PS1""$ \e[0;97m"
		}

	# ------ LINE COMMANDS ------
		PS1="$PS1""${RED}$ \e[0;97m"       # change color to red
		MSYS2_PS1="$PS1"

########################################################################
#                                 ALIAS                                #
########################################################################

if test -f ~/.bash_aliases
then
	source ~/.bash_aliases
fi
